sudo: required
# language: generic
services:
  - docker

before_install:
  - docker build -t fabughazaleh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fabughazaleh/react-test npm run test

after_success:
  - docker build -t fabughazaleh/multi-client ./client
  - docker build -t fabughazaleh/multi-nginx ./nginx
  - docker build -t fabughazaleh/multi-server ./server
  - docker build -t fabughazaleh/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push fabughazaleh/multi-client
  - docker push fabughazaleh/multi-nginx
  - docker push fabughazaleh/multi-server
  - docker push fabughazaleh/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-us-east-1-110264963022"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id:
#     secure: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"